# -*- coding: utf-8 -*-
"""Task 2 - BMI Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fe0CnYvRiPH6Ud548iiCLWP-SOPX34yy

# TASK-2

#Project Title: BMI Calculator

**BMI Calculator**
"""

name=input("Enter your name:")
weight=int(input("Enter your weight in pounds:"))
height=int(input("Enter your height in inches:"))
BMI=(weight*703)/(height*height)
print(BMI)
if BMI>0:
  if(BMI<18.5):
    print(name+",you are underweight.")
  elif(BMI<24.9):
    print(name+",you are normal weight.")
  elif(BMI<29.9):
    print(name+",you are overweight");
  elif(BMI<34.9):
    print(name+",you are obese");
  elif(BMI<39.9):
    print(name+",you are severely obese")
  else:
    print(name+",you are morbidly obese")
else:
  print("Enter valid input")