# -*- coding: utf-8 -*-
"""Task-1 Simple Password Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GgNXTgIxOQJSsOm3eTRCk9qhcyQv6B2

# TASK-1

#Project Title: Simple Password Generator

**Random Password Generator**
"""

import string
import random

if __name__=="__main__":
  s1=string.ascii_lowercase
  s2=string.ascii_uppercase
  s3=string.digits
  s4=string.punctuation

plen=int(input("Enter password length\n"))
s=[]
s.extend(list(s1))
s.extend(list(s2))
s.extend(list(s3))
s.extend(list(s4))
random.shuffle(s)
print("Your password is:")
print("".join(s[0:plen]))